# Generated by Django 5.1.2 on 2024-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.CharField(max_length=100)),
                ("field2", models.CharField(max_length=100)),
                ("field3", models.CharField(max_length=100)),
            ],
        ),
    ]
