# Generated by Django 5.1.2 on 2024-10-23 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
